service: ts-test
# package:
#   individually: true

provider:
  name: aws
  stage: ${opt:stage, "development"}
  region: ${opt:region, "us-east-2"}
  runtime: nodejs8.10
  memorySize: 256
  timeout: 60

  iamRoleStatements:
    - Effect: 'Allow'
      Action:
        - ec2:CreateNetworkInterface
        - ec2:DescribeNetworkInterfaces
        - ec2:DetachNetworkInterface
        - ec2:DeleteNetworkInterface
        - sqs:ChangeMessageVisibility
        - sqs:DeleteMessage
        - sqs:GetQueueAttributes
        - sqs:ReceiveMessage
      Resource: '*'
    - Effect: 'Allow'
      Action:
        - 'sns:Publish'
      Resource: '*'

#
# AWS resources
#
resources:
  Resources:
    #
    # SNS
    #

    # SNS topic for created files
    snsTest:
      Type: 'AWS::SNS::Topic'
      Properties:
        TopicName: CHUNFENG-TEST-${self:provider.stage}

    snsTopicPolicy:
      Type: AWS::SNS::TopicPolicy
      Properties:
        PolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Sid: snsTopicPolicy
              Effect: Allow
              Principal:
                Service: s3.amazonaws.com
              Action: sns:Publish
              Resource: '*'
        Topics:
          - Ref: snsTest

    #
    # SQS
    #

    # SQS - RAW -> ES
    sqsTestDLQ:
      Type: 'AWS::SQS::Queue'
      Properties:
        QueueName: CHUNFENG_TEST_DLQ-${self:provider.stage}
        MessageRetentionPeriod: 1209600

    sqsTest:
      Type: 'AWS::SQS::Queue'
      DependsOn:
        - sqsTestDLQ
      Properties:
        QueueName: CHUNFENG_TEST-${self:provider.stage}
        VisibilityTimeout: 60
        RedrivePolicy:
          maxReceiveCount: 3
          deadLetterTargetArn:
            Fn::GetAtt:
              - sqsTestDLQ
              - Arn

    QueuePolicy:
      Type: AWS::SQS::QueuePolicy
      DependsOn:
        - sqsTest
        - sqsTestDLQ
      Properties:
        Queues:
          - Ref: sqsTest
          - Ref: sqsTestDLQ
        PolicyDocument:
          Id: PushMessageToSQSPolicy
          Version: '2012-10-17'
          Statement:
            - Sid: allow-sns-messages
              Effect: Allow
              Principal:
                AWS: '*'
              Resource: '*'
              Action: sqs:SendMessage
              Condition:
                ArnEquals:
                  aws:SourceArn:
                    Ref: snsTest

functions:
  #
  # Transform a RAW AKTA file to an IDS file (S3)
  #
  chunfengTest:
    handler: index.handler
    memorySize: 1024
    reservedConcurrency: 1
    # package:
    #   include:
    #     - lambdas/rawAktaToIds/**
    #     - resources/**
    #     - utils/**
    description: Chunfeng Test
    environment:
      ENV: ${self:provider.stage}
    events:
      - sns:
          arn:
            Ref: snsTest
          topicName: CHUNFENG-TEST-${self:provider.stage}

plugins:
  - serverless-pseudo-parameters
